routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('content.home');
});


// Route Pelajar //

// Route::get('/', 'PelajarController@index')->name('pelajar.index');
// Route::get('/pelajar/create', 'PelajarController@create')->name('pelajar.create');
// Route::post('/pelajar', 'PelajarController@store')->name('pelajar.store');
// Route::get('/pelajar/{pelajar}', 'PelajarController@show')->name('pelajar.show');
// Route::get('/pelajar/{pelajar}/edit', 'PelajarController@edit')->name('pelajar.edit');
// Route::put('/pelajar/{pelajar}', 'PelajarController@update')->name('pelajar.update');
// Route::delete('/pelajar/{pelajar}', 'PelajarController@destroy')->name('pelajar.destroy');

Route::resource('pelajars', 'PelajarController')->middleware('auth');

// Route guru //

// Route::get('/guru', 'GuruController@index')->name('guru.index');
// Route::get('/guru/create', 'GuruController@create')->name('guru.create');
// Route::post('/guru', 'GuruController@store')->name('guru.store');
// Route::get('/guru/{guru}', 'GuruController@show')->name('guru.show');
// Route::get('/guru/{guru}/edit', 'GuruController@edit')->name('guru.edit');
// Route::put('/guru/{guru}', 'GuruController@update')->name('guru.update');
// Route::delete('/guru/{guru}', 'GuruController@destroy')->name('guru.destroy');

Route::resource('gurus', 'GuruController')->middleware('auth');

// Route web //

Route::get('/kopiku/create', 'PelajarController@createweb')->name('kopiku.create');
Route::post('/kopiku', 'PelajarController@storeweb')->name('kopiku.store');

Route::prefix('/kopiku')->group(function(){
    Route::get('/halaman-utama', function () {
        return view('content.home');
    });
    Route::get('/contactus', function () {
        return view('content.contactus');
    });
    Route::get('/aboutus', function () {
        return view('content.aboutus');
    });
    Route::get('/coffeegrinder', function () {
        return view('content.coffeegrinder');
    });
    Route::get('/coffeebeans', function () {
        return view('content.coffeebeans');
    });
});


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');

app/Guru.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Guru extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/GuruController.php
<?php

namespace App\Http\Controllers;

use App\Guru;
use Illuminate\Http\Request;

class GuruController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $guru = Guru::all();
        return view('guru.index',['guru' => $guru]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('guru.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate([
            'nik' => 'required|size:8|unique:gurus',
            'nama' => 'required|min:3|max:50',
            'jenis_kelamin' => 'required|in:P,L',
            'bagian' => 'required',
            'alamat' => '',
        ]);

        Guru::create($validateData);
        $request->session()->flash('pesan', "Data {$validateData['nama']} berhasil di simpan ");
        return redirect()->route('gurus.index'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function show(Guru $guru)
    {
        return view('guru.show', ['guru' => $guru]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function edit(Guru $guru)
    {
        return view('guru.edit', ['guru' => $guru]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Guru $guru)
    {
        $validateData = $request->validate([
            'nik' => 'required|size:8|unique:gurus,nik,'.$guru->id,
            'nama' => 'required|min:3|max:50',
            'jenis_kelamin' => 'required|in:P,L',
            'bagian' => 'required',
            'alamat' => '',
        ]);
        $guru->update($validateData);
        return redirect()->route('gurus.show',['guru' => $guru->id])->with('pesan', "Update Data {$validateData['nama']} Berhasil");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function destroy(Guru $guru)
    {
        $guru->delete();
        return redirect()->route('gurus.index')->with('pesan', "Hapus Data $guru->nama BERHASIL");
    }
}

resources/views/guru/create.blade.php
@extends('master')

@section('content')
    
<div class="container bg-white">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center"> DATA PEKERJA </h1>
            <hr>
            <form action="{{ route('gurus.store') }} " method="POST">
                @csrf
                <div class="form-group">
                    <label for="nik">NIK</label>
                    <input type="text" class="form-control @error('nik') is-invalid @enderror" id="nik" name="nik" 
                    value="{{ old('nik') }}">
                    @error('nik')
                        <div class="text-danger">  {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="nama">Nama Lengkap</label>
                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" id="nama"
                    value="{{ old('nama') }} ">
                    @error('nama')
                        <div class="text-danger"> {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label>Jenis Kelamin</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="laki_laki" value="L"
                    {{ old('jenis_kelamin')=='L' ? 'checked': '' }} >
                    <label class="form-check-label" for="laki_laki">Laki-laki</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="perempuan" value="P"
                    {{ old('jenis_kelamin')=='P' ? 'checked': '' }} >
                    <label class="form-check-label" for="perempuan">Perempuan</label>
                </div>
                @error('jenis_kelamin')
                    <div class="text-danger"> {{ $message }} </div>
                @enderror

                <div class="form-group">
                    <label for="bagian">Bagian</label>
                    <select class="form-control" name="bagian" id="bagian">
                        <option value="Frontend Developer" {{ old('bagian')=='Frontend Developer' ? 'selected': '' }} >
                            Frontend Developer
                        </option>
                        <option value="Backend Developer" {{ old('bagian')=='Backend Developer' ? 'selected': '' }} >
                            Backend Developer
                        </option>
                        <option value="Fullstack Developer" {{ old('bagian')=='Fullstack Developer' ? 'selected': '' }} >
                            Fullstack Developer
                        </option>
                        <option value="Digital Marketing" {{ old('bagian')=='Digital Marketing' ? 'selected': '' }} >
                            Digital Marketing
                        </option>
                        <option value="UI / UX" {{ old('bagian')=='UI / UX' ? 'selected': '' }} >
                            UI / UX
                        </option>
                    </select>
                    @error('bagian')
                        <div class="text-danger"> {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <textarea name="alamat" id="alamat" rows="3"> {{ old('alamat') }} </textarea>
                </div>

                <button type="submit" class="btn btn-primary mb-2">SIMPAN</button>
                
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/guru/delete.blade.php
@extends('master')

@section('content')
    
<form action=" {{route('gurus.destroy', $guru->id)}} " method="POST">
    @method('DELETE')
    @csrf
    <button type="submit" class="btn btn-danger ml-3">Hapus</button>
    </form>

<hr>
@if (session()->has('pesan'))
    <div class="alert alert-success" role="alert">
        {{ session()->get('pesan') }}
    </div>
@endif

@endsection

resources/views/guru/edit.blade.php
@extends('master')

@section('content')
    
    <div class="container pt-4 bg-white">
        <div class="row">
            <div class="col-md-12">
                <h1>Edit Guru</h1>
                <hr>
                <form action=" {{ route('gurus.update', ['guru' => $guru->id]) }} " method="POST">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="nik">NIK</label>
                        <input type="text" class="form-control @error ('nik') is-invalid @enderror" id="nik" name="nik" value=" {{old('nik') ?? $guru->nik }} ">
                        @error('nik')
                            <div class="text-danger"> {{ $message }} </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="nama">Nama Lengkap</label>
                        <input type="text" class="form-control @error('record') @enderror" id="nama" name="nama" value=" {{ old('nama') ?? $guru->nama }} ">
                        @error('nama')
                            <div class="text-danger"> {{ $message }} </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="">Jenis Kelamin</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" id="laki-laki" value="L" {{ (old('jenis_kelamin') ?? $guru->jenis_kelamin) == 'L' ? 'checked' : '' }}>
                        <label class="form-check-label" for="laki-laki">Laki-laki</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" id="perempuan" value="L" {{ (old('jenis_kelamin') ?? $guru->jenis_kelamin) == 'L' ? 'checked' : '' }}>
                        <label class="form-check-label" for="perempuan">Perempuan</label>
                    </div>
                    @error('jenis_kelamin')
                        <div class="text-danger"> {{ $message }} </div>
                    @enderror

                    <div class="form-group">
                        <label for="bagian">Bagian</label>
                        <select class="form-control" name="bagian" id="bagian">
                            <option value="Frontend Developer" {{ (old('bagian') ?? $guru->bagian) == 'Frontend Developer' ? 'selected' : '' }} >
                                Frontend Developer
                            </option>
                            <option value="Backend Developer" {{ (old('bagian') ?? $guru->bagian) == 'Backend Developer' ? 'selected' : '' }} >
                                Backend Developer
                            </option>
                            <option value="Fullstack Developer" {{ (old('bagian') ?? $guru->bagian) == 'Fullstack Developer' ? 'selected' : '' }} >
                                Fullstack Developer
                            </option>
                            <option value="Digital Marketing" {{ (old('bagian') ?? $guru->bagian) == 'Digital Marketing' ? 'selected' : '' }} >
                                Digital Marketing
                            </option>
                            <option value="UI / UX" {{ (old('bagian') ?? $guru->bagian) == 'UI / UX' ? 'selected' : '' }} >
                                UI / UX
                            </option>
                        </select>
                        @error('bagian')
                            <div class="text-danger"> {{ $message }} </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <textarea name="alamat" id="alamat" rows="3"> {{ old('alamat') ?? $guru->alamat }} </textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Update</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/guru/index.blade.php
@extends('master')

@section('content')

    <div class="container mt-3">
        <div class="row">
            <div class="col-12">
                <div class="py-4">
                    <h1>Tabel Data Guru</h1>
                    <a href=" {{ route('gurus.create') }} " class="btn btn-primary"> Tambah Guru </a>
                </div>

                @if (session() -> has('pesan'))
                    <div class="alert alert-success">
                        {{ session()->get('pesan') }}
                    </div>
                @endif

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nik</th>
                            <th>Nama</th>
                            <Th>Jenis Kelamin</Th>
                            <th>Bagian</th>
                            <th>Alamat</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($guru as $guruz)
                            <tr>

                            </tr>
                            <th>{{ $loop->iteration }}</th>
                            {{-- Method 1 (works!!!) --}}
                            <td><a href="{{ route('gurus.show', ['guru' => $guruz->id]) }}"> {{ $guruz->nik }} </a>
                            </td>

                            <td>{{ $guruz->nama }}</td>
                            <td>{{ $guruz->jenis_kelamin == 'P' ? 'Perempuan' : 'Laki-Laki' }}</td>
                            <td>{{ $guruz->bagian }}</td>
                            <td>{{ $guruz->alamat == '' ? 'N/A' : $guruz->alamat }}</td>
                            <td>
                                <div class="row">
                                    <button class="btn btn-warning"><a style="color: black" href="{{route('gurus.edit', $guruz->id)}}">Edit</a></button>
                                    <form action=" {{route('gurus.destroy', $guruz->id)}} " method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-danger ml-3">Hapus</button>
                                        </form>
                                </div>
                            </td>
                        @empty
                            <td colspan="8" class="text-center">Data Kosong</td>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/guru/show.blade.php
@extends('master')

@section('content')
    
    <div class="container mt-3">
        <div class="row">
            <div class="col-12">
                <div class="pt-3 d-flex justify-content-end align-items-center">
                    <h1 class="h2 mr-auto">Biodata {{$guru->nama}}</h1>
                    <a href=" {{route('gurus.edit', $guru->id)}} " class="btn btn-warning"> UBAH </a>

                    <form action=" {{route('gurus.destroy', $guru->id)}} " method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger ml-3">Hapus</button>
                    </form>
                </div>
                <hr>
                @if (session()->has('pesan'))
                    <div class="alert alert-success" role="alert">
                        {{ session()->get('pesan') }}
                    </div>
                @endif
                <ul>
                    <li> Nik: {{ $guru->nik}} </li>
                    <li> Nama: {{ $guru->nama}} </li>
                    <li> Jenis Kelamin: {{ $guru->jenis_kelamin == 'P' ? 'Perempuan' : 'Laki-laki'}} </li>
                    <li> Bagian: {{ $guru->bagian}} </li>
                    <li> Alamat: {{ $guru->alamat == '' ? 'N/A' : $guru->alamat}} </li>
                </ul>
            </div>
        </div>
    </div>

@endsection