routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('content.home');
});


// Route Pelajar //

// Route::get('/', 'PelajarController@index')->name('pelajar.index');
// Route::get('/pelajar/create', 'PelajarController@create')->name('pelajar.create');
// Route::post('/pelajar', 'PelajarController@store')->name('pelajar.store');
// Route::get('/pelajar/{pelajar}', 'PelajarController@show')->name('pelajar.show');
// Route::get('/pelajar/{pelajar}/edit', 'PelajarController@edit')->name('pelajar.edit');
// Route::put('/pelajar/{pelajar}', 'PelajarController@update')->name('pelajar.update');
// Route::delete('/pelajar/{pelajar}', 'PelajarController@destroy')->name('pelajar.destroy');

Route::resource('pelajars', 'PelajarController')->middleware('auth');

// Route guru //

// Route::get('/guru', 'GuruController@index')->name('guru.index');
// Route::get('/guru/create', 'GuruController@create')->name('guru.create');
// Route::post('/guru', 'GuruController@store')->name('guru.store');
// Route::get('/guru/{guru}', 'GuruController@show')->name('guru.show');
// Route::get('/guru/{guru}/edit', 'GuruController@edit')->name('guru.edit');
// Route::put('/guru/{guru}', 'GuruController@update')->name('guru.update');
// Route::delete('/guru/{guru}', 'GuruController@destroy')->name('guru.destroy');

Route::resource('gurus', 'GuruController')->middleware('auth');

// Route web //

Route::get('/kopiku/create', 'PelajarController@createweb')->name('kopiku.create');
Route::post('/kopiku', 'PelajarController@storeweb')->name('kopiku.store');

Route::prefix('/kopiku')->group(function(){
    Route::get('/halaman-utama', function () {
        return view('content.home');
    });
    Route::get('/contactus', function () {
        return view('content.contactus');
    });
    Route::get('/aboutus', function () {
        return view('content.aboutus');
    });
    Route::get('/coffeegrinder', function () {
        return view('content.coffeegrinder');
    });
    Route::get('/coffeebeans', function () {
        return view('content.coffeebeans');
    });
});


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/login') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>

                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/layouts/footer-web.blade.php
<div class="footer" id="footer-page">
    <div class="container-fluid fluid-footer" style="background-color: #343a40;">
        <div class="container-sm container-footer">
            <div class="row">
                <div class="col-6 col-md-6 col-lg-4">
                    <div class="footer-kiri">
                        <div class="row">
                            <ul class="nav">
                                <li class="nav-item">
                                    <a class="nav-link footer-p" id="footer-p" href="/kopiku/contactus">Subscribes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link footer-p" id="footer-p" href="/kopiku/aboutus">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link footer-p" id="footer-p" href="/kopiku/contactus">Contact Us</a>
                                </li>
                            </ul>
                            <p style="font-size: medium; color: wheat; padding-left: 10px;">
                                Jl.Menceng Raya No.50</p>
                        </div>
                    </div>
                </div>
                <div class="col-6 col-md-6 col-lg-8 ">
                    <div class="footer-kanan ">
                        <div class="row ">
                            <div class="col-12 col-md-4 col-lg-4 ">
                                <!-- kosong -->
                            </div>
                            <div class="col-12 col-md-4 col-lg-4 ">
                                <!-- kosong -->
                            </div>
                            <div class="col-12 col-md-6 col-lg-6 ">
                                <!-- kosong -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/footer.blade.php
<body class="hold-transition sidebar-mini layout-fixed">
<!-- /.content-wrapper -->
  <footer class="main-footer" style="">
    <strong>Copyright &copy; 2014-2019 <a href="#">AdminLTE</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.0
    </div>
  </footer>
</body>

resources/views/layouts/header-web.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" style="line-height: 60px;" id="nav-bar-page">
    <div class="container container-navbar">
        <a class="navbar-brand" href="/kopiku/halaman-utama"><img src="/img/pngwing.com.png" class="img-fluid" style="height: 5rem; width: 10rem;" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto navbar-atas">
                <li class="nav-item active">
                    <a class="nav-link" href="/kopiku/halaman-utama" data-transition="slide">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Products
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item nav-drop-1" href="/kopiku/coffeegrinder">Coffee Grinder</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item nav-drop-2" href="/kopiku/coffeebeans">Coffee Beans</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/kopiku/contactus" id="contactus">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/kopiku/aboutus" data-transition="slide" id="aboutus">About Us</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/header.blade.php
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search"
                        aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <ul class="navbar-nav navbar-login">
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }}
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
            </ul>

        </nav>
        <!-- /.navbar -->
    </div>
    <!-- ./wrapper -->
</body>

resources/views/layouts/sidebar.blade.php
<body class="hold-transition sidebar-mini layout-fixed">
<!-- Main Sidebar Container -->
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!-- Brand Logo -->
                <a href="#" class="brand-link">
                    <img src="https://ecs7.tokopedia.net/img/cache/700/VqbcmM/2020/10/15/c1c6e6df-3f6e-4ffe-b17c-fb9bcc69f6f4.jpg" alt="AdminKopiKu Logo" class="brand-image img-circle elevation-4"
                        style="opacity: 0.8">
                    <span class="brand-text font-weight-light">Admin Kopi-Ku!</span>
                </a>

                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="https://w7.pngwing.com/pngs/164/34/png-transparent-computer-icons-businessperson-user-icon-man-people-logo-black.png" class="img-fluid img-circle elevation-2" alt="User Image">
                        </div>
                        <div class="info">
                            <a href="#" class="d-block">Hendy Hanan</a>
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                            data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
                            <li class="nav-item has-treeview menu-open">
                                <a href="#" class="nav-link active">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        Dashboard
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{{route('pelajars.index')}}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Pelajar</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{route('gurus.index')}}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Guru</p>
                                        </a>
                                    </li>
                                    {{-- <li class="nav-item">
                                        <a href="./index3.html" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Materi</p>
                                        </a>
                                    </li> --}}
                                </ul>
                            </li>
                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
                <!-- /.sidebar -->
            </aside>
            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
</body>