routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('content.home');
});


// Route Pelajar //

// Route::get('/', 'PelajarController@index')->name('pelajar.index');
// Route::get('/pelajar/create', 'PelajarController@create')->name('pelajar.create');
// Route::post('/pelajar', 'PelajarController@store')->name('pelajar.store');
// Route::get('/pelajar/{pelajar}', 'PelajarController@show')->name('pelajar.show');
// Route::get('/pelajar/{pelajar}/edit', 'PelajarController@edit')->name('pelajar.edit');
// Route::put('/pelajar/{pelajar}', 'PelajarController@update')->name('pelajar.update');
// Route::delete('/pelajar/{pelajar}', 'PelajarController@destroy')->name('pelajar.destroy');

Route::resource('pelajars', 'PelajarController')->middleware('auth');

// Route guru //

// Route::get('/guru', 'GuruController@index')->name('guru.index');
// Route::get('/guru/create', 'GuruController@create')->name('guru.create');
// Route::post('/guru', 'GuruController@store')->name('guru.store');
// Route::get('/guru/{guru}', 'GuruController@show')->name('guru.show');
// Route::get('/guru/{guru}/edit', 'GuruController@edit')->name('guru.edit');
// Route::put('/guru/{guru}', 'GuruController@update')->name('guru.update');
// Route::delete('/guru/{guru}', 'GuruController@destroy')->name('guru.destroy');

Route::resource('gurus', 'GuruController')->middleware('auth');

// Route web //

Route::get('/kopiku/create', 'PelajarController@createweb')->name('kopiku.create');
Route::post('/kopiku', 'PelajarController@storeweb')->name('kopiku.store');

Route::prefix('/kopiku')->group(function(){
    Route::get('/halaman-utama', function () {
        return view('content.home');
    });
    Route::get('/contactus', function () {
        return view('content.contactus');
    });
    Route::get('/aboutus', function () {
        return view('content.aboutus');
    });
    Route::get('/coffeegrinder', function () {
        return view('content.coffeegrinder');
    });
    Route::get('/coffeebeans', function () {
        return view('content.coffeebeans');
    });
});


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');

app/Pelajar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pelajar extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/PelajarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pelajar;

class PelajarController extends Controller
{
    public function index()
    {
        // return "Tabel Pendataan Pelajar";
        $pelajar = Pelajar::all();
        return view('pelajar.index',['pelajar' => $pelajar]);
    }

    // public function show($pelajar)
    // {
    //     $result = Pelajar::findorfail($pelajar);
    //     return view('pelajar.show',['pelajar' => $result]);
    // }

    // Method Binding //
    public function show(Pelajar $pelajar)
    {
        return view('pelajar.show', ['pelajar' => $pelajar]);
    }

    public function create()
    {
        return view('pelajar.create');
    }

    public function createweb()
    {
        return view('kopiku.create');
    }

    public function store(Request $request)
    {
        $validateData = $request->validate([
            'nik' => 'required|size:8|unique:pelajars',
            'nama' => 'required|min:3|max:50',
            'jenis_kelamin' => 'required|in:P,L',
            'bagian' => 'required',
            'alamat' => '',
        ]);
        
        // Method 1 //
        // $pelajar = new Pelajar();
        // $pelajar->nik = $validateData['nik'];
        // $pelajar->nama = $validateData['nama'];
        // $pelajar->jenis_kelamin = $validateData['jenis_kelamin'];
        // $pelajar->bagian = $validateData['bagian'];
        // $pelajar->alamat = $validateData['alamat'];
        // $pelajar->save();
        // return "Data Berhasil Disimpan";

        // Method Mass Assignment //
        Pelajar::create($validateData);
        $request->session()->flash('pesan', "Data {$validateData['nama']} berhasil di simpan ");
        return redirect()->route('pelajars.index');   
    }

    public function storeweb(Request $request)
    {
        $validateData = $request->validate([
            'nik' => 'required|size:8|unique:pelajars',
            'nama' => 'required|min:3|max:50',
            'jenis_kelamin' => 'required|in:P,L',
            'bagian' => 'required',
            'alamat' => '',
        ]);

        // Method Mass Assignment //
        Pelajar::create($validateData);
        $request->session()->flash('pesan', "Data {$validateData['nama']} berhasil di simpan ");
        return redirect('/kopiku/contactus');   
    }


    public function edit(Pelajar $pelajar)
    {
        return view('pelajar.edit', ['pelajar' => $pelajar]);
    }

    public function update(Request $request, Pelajar $pelajar)
    {
        $validateData = $request->validate([
            'nik' => 'required|size:8|unique:pelajars,nik,'.$pelajar->id,
            'nama' => 'required|min:3|max:50',
            'jenis_kelamin' => 'required|in:P,L',
            'bagian' => 'required',
            'alamat' => '',
        ]);
        $pelajar->update($validateData);
        return redirect()->route('pelajars.show',['pelajar' => $pelajar->id])->with('pesan', "Update Data {$validateData['nama']} Berhasil");
    }

    public function destroy(Pelajar $pelajar)
    {
        $pelajar->delete();
        return redirect()->route('pelajars.index')->with('pesan', "Hapus Data $pelajar->nama BERHASIL");
    }
}

resources/views/pelajar/create.blade.php
@extends('master')

@section('content')
    
<div class="container bg-white">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center"> DATA PELAJAR </h1>
            <form action="{{ route('pelajars.store') }} " method="POST">
                @csrf
                <div class="form-group">
                    <label for="nik">NIK</label>
                    <input type="text" class="form-control @error('nik') is-invalid @enderror" id="nik" name="nik" 
                    value="{{ old('nik') }}">
                    @error('nik')
                        <div class="text-danger">  {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="nama">Nama Lengkap</label>
                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" id="nama"
                    value="{{ old('nama') }} ">
                    @error('nama')
                        <div class="text-danger"> {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label>Jenis Kelamin</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="laki_laki" value="L"
                    {{ old('jenis_kelamin')=='L' ? 'checked': '' }} >
                    <label class="form-check-label" for="laki_laki">Laki-laki</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="perempuan" value="P"
                    {{ old('jenis_kelamin')=='P' ? 'checked': '' }} >
                    <label class="form-check-label" for="perempuan">Perempuan</label>
                </div>
                @error('jenis_kelamin')
                    <div class="text-danger"> {{ $message }} </div>
                @enderror

                <div class="form-group">
                    <label for="bagian">Bagian</label>
                    <select class="form-control" name="bagian" id="bagian">
                        <option value="Frontend Developer" {{ old('bagian')=='Frontend Developer' ? 'selected': '' }} >
                            Frontend Developer
                        </option>
                        <option value="Backend Developer" {{ old('bagian')=='Backend Developer' ? 'selected': '' }} >
                            Backend Developer
                        </option>
                        <option value="Fullstack Developer" {{ old('bagian')=='Fullstack Developer' ? 'selected': '' }} >
                            Fullstack Developer
                        </option>
                        <option value="Digital Marketing" {{ old('bagian')=='Digital Marketing' ? 'selected': '' }} >
                            Digital Marketing
                        </option>
                        <option value="UI / UX" {{ old('bagian')=='UI / UX' ? 'selected': '' }} >
                            UI / UX
                        </option>
                    </select>
                    @error('bagian')
                        <div class="text-danger"> {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <textarea name="alamat" id="alamat" rows="3"> {{ old('alamat') }} </textarea>
                </div>

                <button type="submit" class="btn btn-primary mb-2">SIMPAN</button>
                
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/pelajar/createweb.blade.php
@extends('master')

@section('content')
    
<div class="container bg-white">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center"> DATA PELAJAR </h1>
            <form action="{{ route('kopiku.store') }} " method="POST">
                @csrf
                <div class="form-group">
                    <label for="nik">NIK</label>
                    <input type="text" class="form-control @error('nik') is-invalid @enderror" id="nik" name="nik" 
                    value="{{ old('nik') }}">
                    @error('nik')
                        <div class="text-danger">  {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="nama">Nama Lengkap</label>
                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" id="nama"
                    value="{{ old('nama') }} ">
                    @error('nama')
                        <div class="text-danger"> {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label>Jenis Kelamin</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="laki_laki" value="L"
                    {{ old('jenis_kelamin')=='L' ? 'checked': '' }} >
                    <label class="form-check-label" for="laki_laki">Laki-laki</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="perempuan" value="P"
                    {{ old('jenis_kelamin')=='P' ? 'checked': '' }} >
                    <label class="form-check-label" for="perempuan">Perempuan</label>
                </div>
                @error('jenis_kelamin')
                    <div class="text-danger"> {{ $message }} </div>
                @enderror

                <div class="form-group">
                    <label for="bagian">Bagian</label>
                    <select class="form-control" name="bagian" id="bagian">
                        <option value="Frontend Developer" {{ old('bagian')=='Frontend Developer' ? 'selected': '' }} >
                            Frontend Developer
                        </option>
                        <option value="Backend Developer" {{ old('bagian')=='Backend Developer' ? 'selected': '' }} >
                            Backend Developer
                        </option>
                        <option value="Fullstack Developer" {{ old('bagian')=='Fullstack Developer' ? 'selected': '' }} >
                            Fullstack Developer
                        </option>
                        <option value="Digital Marketing" {{ old('bagian')=='Digital Marketing' ? 'selected': '' }} >
                            Digital Marketing
                        </option>
                        <option value="UI / UX" {{ old('bagian')=='UI / UX' ? 'selected': '' }} >
                            UI / UX
                        </option>
                    </select>
                    @error('bagian')
                        <div class="text-danger"> {{ $message }} </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <textarea name="alamat" id="alamat" rows="3"> {{ old('alamat') }} </textarea>
                </div>

                <button type="submit" class="btn btn-primary mb-2">SIMPAN</button>
                
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/pelajar/delete.blade.php
@extends('master')

@section('content')
    
<form action=" {{route('pelajars.destroy', $pelajar->id)}} " method="POST">
    @method('DELETE')
    @csrf
    <button type="submit" class="btn btn-danger ml-3">Hapus</button>
    </form>

<hr>
@if (session()->has('pesan'))
    <div class="alert alert-success" role="alert">
        {{ session()->get('pesan') }}
    </div>
@endif

@endsection

resources/views/pelajar/edit.blade.php
@extends('master')

@section('content')
    
    <div class="container pt-4 bg-white">
        <div class="row">
            <div class="col-md-12">
                <h1>Edit Pelajar</h1>
                <hr>
                <form action=" {{ route('pelajars.update', ['pelajar' => $pelajar->id]) }} " method="POST">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="nik">NIK</label>
                        <input type="text" class="form-control @error ('nik') is-invalid @enderror" id="nik" name="nik" value=" {{old('nik') ?? $pelajar->nik }} ">
                        @error('nik')
                            <div class="text-danger"> {{ $message }} </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="nama">Nama Lengkap</label>
                        <input type="text" class="form-control @error('record') @enderror" id="nama" name="nama" value=" {{ old('nama') ?? $pelajar->nama }} ">
                        @error('nama')
                            <div class="text-danger"> {{ $message }} </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="">Jenis Kelamin</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" id="laki-laki" value="L" {{ (old('jenis_kelamin') ?? $pelajar->jenis_kelamin) == 'L' ? 'checked' : '' }}>
                        <label class="form-check-label" for="laki-laki">Laki-laki</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" id="perempuan" value="L" {{ (old('jenis_kelamin') ?? $pelajar->jenis_kelamin) == 'L' ? 'checked' : '' }}>
                        <label class="form-check-label" for="perempuan">Perempuan</label>
                    </div>
                    @error('jenis_kelamin')
                        <div class="text-danger"> {{ $message }} </div>
                    @enderror

                    <div class="form-group">
                        <label for="bagian">Bagian</label>
                        <select class="form-control" name="bagian" id="bagian">
                            <option value="Frontend Developer" {{ (old('bagian') ?? $pelajar->bagian) == 'Frontend Developer' ? 'selected' : '' }} >
                                Frontend Developer
                            </option>
                            <option value="Backend Developer" {{ (old('bagian') ?? $pelajar->bagian) == 'Backend Developer' ? 'selected' : '' }} >
                                Backend Developer
                            </option>
                            <option value="Fullstack Developer" {{ (old('bagian') ?? $pelajar->bagian) == 'Fullstack Developer' ? 'selected' : '' }} >
                                Fullstack Developer
                            </option>
                            <option value="Digital Marketing" {{ (old('bagian') ?? $pelajar->bagian) == 'Digital Marketing' ? 'selected' : '' }} >
                                Digital Marketing
                            </option>
                            <option value="UI / UX" {{ (old('bagian') ?? $pelajar->bagian) == 'UI / UX' ? 'selected' : '' }} >
                                UI / UX
                            </option>
                        </select>
                        @error('bagian')
                            <div class="text-danger"> {{ $message }} </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <textarea name="alamat" id="alamat" rows="3"> {{ old('alamat') ?? $pelajar->alamat }} </textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Update</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/pelajar/index.blade.php
@extends('master')

@section('content')

    <div class="container mt-3">
        <div class="row">
            <div class="col-12">
                <div class="py-4">
                    <h1>Tabel Data Pelajar</h1>
                    <a href=" {{ route('pelajars.create') }} " class="btn btn-primary"> Tambah Pelajar </a>
                </div>

                @if (session() -> has('pesan'))
                    <div class="alert alert-success">
                        {{ session()->get('pesan') }}
                    </div>
                @endif

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nik</th>
                            <th>Nama</th>
                            <Th>Jenis Kelamin</Th>
                            <th>Bagian</th>
                            <th>Alamat</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($pelajar as $pelajarz)
                            <tr>

                            </tr>
                            <th>{{ $loop->iteration }}</th>
                            {{-- Method 1 (works!!!) --}}
                            <td><a href="{{ route('pelajars.show', ['pelajar' => $pelajarz->id]) }}"> {{ $pelajarz->nik }} </a>
                            </td>
                            {{-- Method 2 (ga works) --}}
                            {{-- <td><a href=" {{ url('/pelajar/', $pelajarz->id) }}">
                                    {{ $pelajarz->nik }} </a></td> --}}
                            <td>{{ $pelajarz->nama }}</td>
                            <td>{{ $pelajarz->jenis_kelamin == 'P' ? 'Perempuan' : 'Laki-Laki' }}</td>
                            <td>{{ $pelajarz->bagian }}</td>
                            <td>{{ $pelajarz->alamat == '' ? 'N/A' : $pelajarz->alamat }}</td>
                            <td>
                                <div class="row">
                                    <button class="btn btn-warning"><a style="color: black" href="{{route('pelajars.edit', $pelajarz->id)}}">Edit</a></button>
                                    <form action=" {{route('pelajars.destroy', $pelajarz->id)}} " method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-danger ml-3">Hapus</button>
                                        </form>
                                </div>
                            </td>
                        @empty
                            <td colspan="8" class="text-center">Data Kosong</td>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/pelajar/show.blade.php
@extends('master')

@section('content')
    
    <div class="container mt-3">
        <div class="row">
            <div class="col-12">
                <div class="pt-3 d-flex justify-content-end align-items-center">
                    <h1 class="h2 mr-auto">Biodata {{$pelajar->nama}}</h1>
                    <a href=" {{route('pelajars.edit', $pelajar->id)}} " class="btn btn-warning"> UBAH </a>

                    <form action=" {{route('pelajars.destroy', $pelajar->id)}} " method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger ml-3">Hapus</button>
                    </form>
                </div>
                <hr>
                @if (session()->has('pesan'))
                    <div class="alert alert-success" role="alert">
                        {{ session()->get('pesan') }}
                    </div>
                @endif
                <ul>
                    <li> Nik: {{ $pelajar->nik}} </li>
                    <li> Nama: {{ $pelajar->nama}} </li>
                    <li> Jenis Kelamin: {{ $pelajar->jenis_kelamin == 'P' ? 'Perempuan' : 'Laki-laki'}} </li>
                    <li> Bagian: {{ $pelajar->bagian}} </li>
                    <li> Alamat: {{ $pelajar->alamat == '' ? 'N/A' : $pelajar->alamat}} </li>
                </ul>
            </div>
        </div>
    </div>

@endsection